### ISSUE TITLE
Help with lab 8

### ISSUE THREAD

**Issue by Shock4an** [oleksandrblazhko/ai-214-zhevneryuk#23]
Доброго вечора, чи можна запитати в чому помилка у мене в 8й лабораторній, бо я не зміг бути присутнім із-за світла на перевірці роботи. Чи можна про це дізнатись тільки на консультації?
Хочу встигнути ще зробити 9-ту лабораторну, але в ній є завдання на основі 8-й.
Завчасно дякую за відповідь!

**Comment by oleksandrblazhko** [comment]
Чекаю на рішення 9-ї роботи у ранку середи.
